name: PullRequest

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      lib-version: 1.0.${{ github.event.pull_request.number }}.${{ github.run_number }}
      configuration: Release
    secrets: inherit
